// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

public final class APIResponseType {
  private APIResponseType() { }
  public static final byte NONE = 0;
  public static final byte CreateHostedGameResponse = 1;
  public static final byte DestroyGameResponse = 2;
  public static final byte GetJoinableGamesResponse = 3;
  public static final byte JoinGameResponse = 4;
  public static final byte LogInResponse = 5;
  public static final byte LogOutResponse = 6;
  public static final byte CommandResponse = 7;
  public static final byte EndGameResponse = 8;
  public static final byte GameUpdateResponse = 9;
  public static final byte SendChatResponse = 10;

  public static final String[] names = { "NONE", "CreateHostedGameResponse", "DestroyGameResponse", "GetJoinableGamesResponse", "JoinGameResponse", "LogInResponse", "LogOutResponse", "CommandResponse", "EndGameResponse", "GameUpdateResponse", "SendChatResponse", };

  public static String name(int e) { return names[e]; }
}

