// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

public final class APIRequestType {
  private APIRequestType() { }
  public static final byte NONE = 0;
  public static final byte CreateHostedGameRequest = 1;
  public static final byte DestroyGameRequest = 2;
  public static final byte GetJoinableGamesRequest = 3;
  public static final byte JoinGameRequest = 4;
  public static final byte LogInRequest = 5;
  public static final byte LogOutRequest = 6;
  public static final byte CommandRequest = 7;
  public static final byte EndGameRequest = 8;
  public static final byte GameUpdateRequestTryToStartGame = 9;
  public static final byte GameUpdateRequestChangeStatus = 10;
  public static final byte GameUpdateRequestAIToHuman = 11;
  public static final byte SendChatRequest = 12;

  public static final String[] names = { "NONE", "CreateHostedGameRequest", "DestroyGameRequest", "GetJoinableGamesRequest", "JoinGameRequest", "LogInRequest", "LogOutRequest", "CommandRequest", "EndGameRequest", "GameUpdateRequestTryToStartGame", "GameUpdateRequestChangeStatus", "GameUpdateRequestAIToHuman", "SendChatRequest", };

  public static String name(int e) { return names[e]; }
}

