// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class APIResponse extends Table {
  public static APIResponse getRootAsAPIResponse(ByteBuffer _bb) { return getRootAsAPIResponse(_bb, new APIResponse()); }
  public static APIResponse getRootAsAPIResponse(ByteBuffer _bb, APIResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public APIResponse __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte responseType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table response(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static int createAPIResponse(FlatBufferBuilder builder,
      byte response_type,
      int responseOffset) {
    builder.startObject(2);
    APIResponse.addResponse(builder, responseOffset);
    APIResponse.addResponseType(builder, response_type);
    return APIResponse.endAPIResponse(builder);
  }

  public static void startAPIResponse(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addResponseType(FlatBufferBuilder builder, byte responseType) { builder.addByte(0, responseType, 0); }
  public static void addResponse(FlatBufferBuilder builder, int responseOffset) { builder.addOffset(1, responseOffset, 0); }
  public static int endAPIResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishAPIResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

