// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class APIRequest extends Table {
  public static APIRequest getRootAsAPIRequest(ByteBuffer _bb) { return getRootAsAPIRequest(_bb, new APIRequest()); }
  public static APIRequest getRootAsAPIRequest(ByteBuffer _bb, APIRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public APIRequest __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte requestType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table request(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static int createAPIRequest(FlatBufferBuilder builder,
      byte request_type,
      int requestOffset) {
    builder.startObject(2);
    APIRequest.addRequest(builder, requestOffset);
    APIRequest.addRequestType(builder, request_type);
    return APIRequest.endAPIRequest(builder);
  }

  public static void startAPIRequest(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addRequestType(FlatBufferBuilder builder, byte requestType) { builder.addByte(0, requestType, 0); }
  public static void addRequest(FlatBufferBuilder builder, int requestOffset) { builder.addOffset(1, requestOffset, 0); }
  public static int endAPIRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishAPIRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

