// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

public final class AssetCapabilityType {
  private AssetCapabilityType() { }
  public static final byte None = 0;
  public static final byte BuildPeasant = 1;
  public static final byte BuildFootman = 2;
  public static final byte BuildArcher = 3;
  public static final byte BuildRanger = 4;
  public static final byte BuildFarm = 5;
  public static final byte BuildTownHall = 6;
  public static final byte BuildBarracks = 7;
  public static final byte BuildLumberMill = 8;
  public static final byte BuildBlacksmith = 9;
  public static final byte BuildKeep = 10;
  public static final byte BuildCastle = 11;
  public static final byte BuildScoutTower = 12;
  public static final byte BuildGuardTower = 13;
  public static final byte BuildCannonTower = 14;
  public static final byte Move = 15;
  public static final byte Repair = 16;
  public static final byte Mine = 17;
  public static final byte BuildSimple = 18;
  public static final byte BuildAdvanced = 19;
  public static final byte Convey = 20;
  public static final byte Cancel = 21;
  public static final byte BuildWall = 22;
  public static final byte Attack = 23;
  public static final byte StandGround = 24;
  public static final byte Patrol = 25;
  public static final byte WeaponUpgrade1 = 26;
  public static final byte WeaponUpgrade2 = 27;
  public static final byte WeaponUpgrade3 = 28;
  public static final byte ArrowUpgrade1 = 29;
  public static final byte ArrowUpgrade2 = 30;
  public static final byte ArrowUpgrade3 = 31;
  public static final byte ArmorUpgrade1 = 32;
  public static final byte ArmorUpgrade2 = 33;
  public static final byte ArmorUpgrade3 = 34;
  public static final byte Longbow = 35;
  public static final byte RangerScouting = 36;
  public static final byte Marksmanship = 37;

  public static final String[] names = { "None", "BuildPeasant", "BuildFootman", "BuildArcher", "BuildRanger", "BuildFarm", "BuildTownHall", "BuildBarracks", "BuildLumberMill", "BuildBlacksmith", "BuildKeep", "BuildCastle", "BuildScoutTower", "BuildGuardTower", "BuildCannonTower", "Move", "Repair", "Mine", "BuildSimple", "BuildAdvanced", "Convey", "Cancel", "BuildWall", "Attack", "StandGround", "Patrol", "WeaponUpgrade1", "WeaponUpgrade2", "WeaponUpgrade3", "ArrowUpgrade1", "ArrowUpgrade2", "ArrowUpgrade3", "ArmorUpgrade1", "ArmorUpgrade2", "ArmorUpgrade3", "Longbow", "RangerScouting", "Marksmanship", };

  public static String name(int e) { return names[e]; }
}

