// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

public final class Color {
  private Color() { }
  public static final byte None = 0;
  public static final byte Blue = 1;
  public static final byte Red = 2;
  public static final byte Green = 3;
  public static final byte Purple = 4;
  public static final byte Orange = 5;
  public static final byte Yellow = 6;
  public static final byte Black = 7;
  public static final byte White = 8;

  public static final String[] names = { "None", "Blue", "Red", "Green", "Purple", "Orange", "Yellow", "Black", "White", };

  public static String name(int e) { return names[e]; }
}

