// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

public final class Difficulty {
  private Difficulty() { }
  public static final byte Easy = 0;
  public static final byte Medium = 1;
  public static final byte Hard = 2;

  public static final String[] names = { "Easy", "Medium", "Hard", };

  public static String name(int e) { return names[e]; }
}

