// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GameUpdateRequestChangeStatus extends Table {
  public static GameUpdateRequestChangeStatus getRootAsGameUpdateRequestChangeStatus(ByteBuffer _bb) { return getRootAsGameUpdateRequestChangeStatus(_bb, new GameUpdateRequestChangeStatus()); }
  public static GameUpdateRequestChangeStatus getRootAsGameUpdateRequestChangeStatus(ByteBuffer _bb, GameUpdateRequestChangeStatus obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public GameUpdateRequestChangeStatus __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String host() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer hostAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String username() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer usernameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public byte playerStatus() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createGameUpdateRequestChangeStatus(FlatBufferBuilder builder,
      int hostOffset,
      int usernameOffset,
      byte playerStatus) {
    builder.startObject(3);
    GameUpdateRequestChangeStatus.addUsername(builder, usernameOffset);
    GameUpdateRequestChangeStatus.addHost(builder, hostOffset);
    GameUpdateRequestChangeStatus.addPlayerStatus(builder, playerStatus);
    return GameUpdateRequestChangeStatus.endGameUpdateRequestChangeStatus(builder);
  }

  public static void startGameUpdateRequestChangeStatus(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addHost(FlatBufferBuilder builder, int hostOffset) { builder.addOffset(0, hostOffset, 0); }
  public static void addUsername(FlatBufferBuilder builder, int usernameOffset) { builder.addOffset(1, usernameOffset, 0); }
  public static void addPlayerStatus(FlatBufferBuilder builder, byte playerStatus) { builder.addByte(2, playerStatus, 0); }
  public static int endGameUpdateRequestChangeStatus(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishGameUpdateRequestChangeStatusBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

