// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GameUpdateResponse extends Table {
  public static GameUpdateResponse getRootAsGameUpdateResponse(ByteBuffer _bb) { return getRootAsGameUpdateResponse(_bb, new GameUpdateResponse()); }
  public static GameUpdateResponse getRootAsGameUpdateResponse(ByteBuffer _bb, GameUpdateResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public GameUpdateResponse __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public com.ecs160.fbs.Game game() { return game(new com.ecs160.fbs.Game()); }
  public com.ecs160.fbs.Game game(com.ecs160.fbs.Game obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createGameUpdateResponse(FlatBufferBuilder builder,
      int gameOffset) {
    builder.startObject(1);
    GameUpdateResponse.addGame(builder, gameOffset);
    return GameUpdateResponse.endGameUpdateResponse(builder);
  }

  public static void startGameUpdateResponse(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addGame(FlatBufferBuilder builder, int gameOffset) { builder.addOffset(0, gameOffset, 0); }
  public static int endGameUpdateResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishGameUpdateResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

