// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GetJoinableGamesRequest extends Table {
  public static GetJoinableGamesRequest getRootAsGetJoinableGamesRequest(ByteBuffer _bb) { return getRootAsGetJoinableGamesRequest(_bb, new GetJoinableGamesRequest()); }
  public static GetJoinableGamesRequest getRootAsGetJoinableGamesRequest(ByteBuffer _bb, GetJoinableGamesRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public GetJoinableGamesRequest __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String player() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer playerAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createGetJoinableGamesRequest(FlatBufferBuilder builder,
      int playerOffset) {
    builder.startObject(1);
    GetJoinableGamesRequest.addPlayer(builder, playerOffset);
    return GetJoinableGamesRequest.endGetJoinableGamesRequest(builder);
  }

  public static void startGetJoinableGamesRequest(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addPlayer(FlatBufferBuilder builder, int playerOffset) { builder.addOffset(0, playerOffset, 0); }
  public static int endGetJoinableGamesRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishGetJoinableGamesRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

