// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class LogInResponse extends Table {
  public static LogInResponse getRootAsLogInResponse(ByteBuffer _bb) { return getRootAsLogInResponse(_bb, new LogInResponse()); }
  public static LogInResponse getRootAsLogInResponse(ByteBuffer _bb, LogInResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public LogInResponse __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte status() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createLogInResponse(FlatBufferBuilder builder,
      byte status) {
    builder.startObject(1);
    LogInResponse.addStatus(builder, status);
    return LogInResponse.endLogInResponse(builder);
  }

  public static void startLogInResponse(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addStatus(FlatBufferBuilder builder, byte status) { builder.addByte(0, status, 0); }
  public static int endLogInResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishLogInResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

