// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class LogInRequest extends Table {
  public static LogInRequest getRootAsLogInRequest(ByteBuffer _bb) { return getRootAsLogInRequest(_bb, new LogInRequest()); }
  public static LogInRequest getRootAsLogInRequest(ByteBuffer _bb, LogInRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public LogInRequest __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public com.ecs160.fbs.UserCredentials credentials() { return credentials(new com.ecs160.fbs.UserCredentials()); }
  public com.ecs160.fbs.UserCredentials credentials(com.ecs160.fbs.UserCredentials obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createLogInRequest(FlatBufferBuilder builder,
      int credentialsOffset) {
    builder.startObject(1);
    LogInRequest.addCredentials(builder, credentialsOffset);
    return LogInRequest.endLogInRequest(builder);
  }

  public static void startLogInRequest(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addCredentials(FlatBufferBuilder builder, int credentialsOffset) { builder.addOffset(0, credentialsOffset, 0); }
  public static int endLogInRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishLogInRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

