// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class LogOutRequest extends Table {
  public static LogOutRequest getRootAsLogOutRequest(ByteBuffer _bb) { return getRootAsLogOutRequest(_bb, new LogOutRequest()); }
  public static LogOutRequest getRootAsLogOutRequest(ByteBuffer _bb, LogOutRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public LogOutRequest __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String username() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer usernameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createLogOutRequest(FlatBufferBuilder builder,
      int usernameOffset) {
    builder.startObject(1);
    LogOutRequest.addUsername(builder, usernameOffset);
    return LogOutRequest.endLogOutRequest(builder);
  }

  public static void startLogOutRequest(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addUsername(FlatBufferBuilder builder, int usernameOffset) { builder.addOffset(0, usernameOffset, 0); }
  public static int endLogOutRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishLogOutRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

