// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

public final class PlayerStatus {
  private PlayerStatus() { }
  public static final byte Ready = 0;
  public static final byte NotReady = 1;

  public static final String[] names = { "Ready", "NotReady", };

  public static String name(int e) { return names[e]; }
}

