// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

public final class PlayerColor {
  private PlayerColor() { }
  public static final byte pcNone = 0;
  public static final byte pcBlue = 1;
  public static final byte pcRed = 2;
  public static final byte pcGreen = 3;
  public static final byte pcPurple = 4;
  public static final byte pcOrange = 5;
  public static final byte pcYellow = 6;
  public static final byte pcBlack = 7;
  public static final byte pcWhite = 8;
  public static final byte pcMax = 9;

  public static final String[] names = { "pcNone", "pcBlue", "pcRed", "pcGreen", "pcPurple", "pcOrange", "pcYellow", "pcBlack", "pcWhite", "pcMax", };

  public static String name(int e) { return names[e]; }
}

