// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PlayerSession extends Table {
  public static PlayerSession getRootAsPlayerSession(ByteBuffer _bb) { return getRootAsPlayerSession(_bb, new PlayerSession()); }
  public static PlayerSession getRootAsPlayerSession(ByteBuffer _bb, PlayerSession obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public PlayerSession __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String sessionId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer sessionIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createPlayerSession(FlatBufferBuilder builder,
      int session_idOffset) {
    builder.startObject(1);
    PlayerSession.addSessionId(builder, session_idOffset);
    return PlayerSession.endPlayerSession(builder);
  }

  public static void startPlayerSession(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addSessionId(FlatBufferBuilder builder, int sessionIdOffset) { builder.addOffset(0, sessionIdOffset, 0); }
  public static int endPlayerSession(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishPlayerSessionBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

