// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

public final class PlayerType {
  private PlayerType() { }
  public static final byte EasyAI = 0;
  public static final byte MediumAI = 1;
  public static final byte HardAI = 2;
  public static final byte Human = 3;
  public static final byte Open = 4;

  public static final String[] names = { "EasyAI", "MediumAI", "HardAI", "Human", "Open", };

  public static String name(int e) { return names[e]; }
}

