// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SendChatRequest extends Table {
  public static SendChatRequest getRootAsSendChatRequest(ByteBuffer _bb) { return getRootAsSendChatRequest(_bb, new SendChatRequest()); }
  public static SendChatRequest getRootAsSendChatRequest(ByteBuffer _bb, SendChatRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public SendChatRequest __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String host() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer hostAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String content() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createSendChatRequest(FlatBufferBuilder builder,
      int hostOffset,
      int contentOffset) {
    builder.startObject(2);
    SendChatRequest.addContent(builder, contentOffset);
    SendChatRequest.addHost(builder, hostOffset);
    return SendChatRequest.endSendChatRequest(builder);
  }

  public static void startSendChatRequest(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addHost(FlatBufferBuilder builder, int hostOffset) { builder.addOffset(0, hostOffset, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(1, contentOffset, 0); }
  public static int endSendChatRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishSendChatRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

