// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SendEndGameResultsResponse extends Table {
  public static SendEndGameResultsResponse getRootAsSendEndGameResultsResponse(ByteBuffer _bb) { return getRootAsSendEndGameResultsResponse(_bb, new SendEndGameResultsResponse()); }
  public static SendEndGameResultsResponse getRootAsSendEndGameResultsResponse(ByteBuffer _bb, SendEndGameResultsResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SendEndGameResultsResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte status() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createSendEndGameResultsResponse(FlatBufferBuilder builder,
      byte status) {
    builder.startObject(1);
    SendEndGameResultsResponse.addStatus(builder, status);
    return SendEndGameResultsResponse.endSendEndGameResultsResponse(builder);
  }

  public static void startSendEndGameResultsResponse(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addStatus(FlatBufferBuilder builder, byte status) { builder.addByte(0, status, 0); }
  public static int endSendEndGameResultsResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishSendEndGameResultsResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

