// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StartGameRequest extends Table {
  public static StartGameRequest getRootAsStartGameRequest(ByteBuffer _bb) { return getRootAsStartGameRequest(_bb, new StartGameRequest()); }
  public static StartGameRequest getRootAsStartGameRequest(ByteBuffer _bb, StartGameRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public StartGameRequest __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String host() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer hostAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public com.ecs160.fbs.Game game() { return game(new com.ecs160.fbs.Game()); }
  public com.ecs160.fbs.Game game(com.ecs160.fbs.Game obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createStartGameRequest(FlatBufferBuilder builder,
      int hostOffset,
      int gameOffset) {
    builder.startObject(2);
    StartGameRequest.addGame(builder, gameOffset);
    StartGameRequest.addHost(builder, hostOffset);
    return StartGameRequest.endStartGameRequest(builder);
  }

  public static void startStartGameRequest(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addHost(FlatBufferBuilder builder, int hostOffset) { builder.addOffset(0, hostOffset, 0); }
  public static void addGame(FlatBufferBuilder builder, int gameOffset) { builder.addOffset(1, gameOffset, 0); }
  public static int endStartGameRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishStartGameRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

