// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

public final class Status {
  private Status() { }
  public static final byte Success = 0;
  public static final byte Failure = 1;
  public static final byte Invalid = 2;
  public static final byte InsufficientPrivileges = 3;

  public static final String[] names = { "Success", "Failure", "Invalid", "InsufficientPrivileges", };

  public static String name(int e) { return names[e]; }
}

