// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

public final class TargetType {
  private TargetType() { }
  public static final byte None = 0;
  public static final byte Peasant = 1;
  public static final byte Footman = 2;
  public static final byte Archer = 3;
  public static final byte Ranger = 4;
  public static final byte GoldMine = 5;
  public static final byte TownHall = 6;
  public static final byte Keep = 7;
  public static final byte Castle = 8;
  public static final byte Farm = 9;
  public static final byte Barracks = 10;
  public static final byte LumberMill = 11;
  public static final byte Blacksmith = 12;
  public static final byte ScoutTower = 13;
  public static final byte GuardTower = 14;
  public static final byte CannonTower = 15;

  public static final String[] names = { "None", "Peasant", "Footman", "Archer", "Ranger", "GoldMine", "TownHall", "Keep", "Castle", "Farm", "Barracks", "LumberMill", "Blacksmith", "ScoutTower", "GuardTower", "CannonTower", };

  public static String name(int e) { return names[e]; }
}

