// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UpdateGameRequest extends Table {
  public static UpdateGameRequest getRootAsUpdateGameRequest(ByteBuffer _bb) { return getRootAsUpdateGameRequest(_bb, new UpdateGameRequest()); }
  public static UpdateGameRequest getRootAsUpdateGameRequest(ByteBuffer _bb, UpdateGameRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public UpdateGameRequest __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String username() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer usernameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String host() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer hostAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public com.ecs160.fbs.Game game() { return game(new com.ecs160.fbs.Game()); }
  public com.ecs160.fbs.Game game(com.ecs160.fbs.Game obj) { int o = __offset(8); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createUpdateGameRequest(FlatBufferBuilder builder,
      int usernameOffset,
      int hostOffset,
      int gameOffset) {
    builder.startObject(3);
    UpdateGameRequest.addGame(builder, gameOffset);
    UpdateGameRequest.addHost(builder, hostOffset);
    UpdateGameRequest.addUsername(builder, usernameOffset);
    return UpdateGameRequest.endUpdateGameRequest(builder);
  }

  public static void startUpdateGameRequest(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addUsername(FlatBufferBuilder builder, int usernameOffset) { builder.addOffset(0, usernameOffset, 0); }
  public static void addHost(FlatBufferBuilder builder, int hostOffset) { builder.addOffset(1, hostOffset, 0); }
  public static void addGame(FlatBufferBuilder builder, int gameOffset) { builder.addOffset(2, gameOffset, 0); }
  public static int endUpdateGameRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishUpdateGameRequestBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

