// automatically generated by the FlatBuffers compiler, do not modify

package com.ecs160.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UpdateGameResponse extends Table {
  public static UpdateGameResponse getRootAsUpdateGameResponse(ByteBuffer _bb) { return getRootAsUpdateGameResponse(_bb, new UpdateGameResponse()); }
  public static UpdateGameResponse getRootAsUpdateGameResponse(ByteBuffer _bb, UpdateGameResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public UpdateGameResponse __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte status() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public com.ecs160.fbs.Game game() { return game(new com.ecs160.fbs.Game()); }
  public com.ecs160.fbs.Game game(com.ecs160.fbs.Game obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createUpdateGameResponse(FlatBufferBuilder builder,
      byte status,
      int gameOffset) {
    builder.startObject(2);
    UpdateGameResponse.addGame(builder, gameOffset);
    UpdateGameResponse.addStatus(builder, status);
    return UpdateGameResponse.endUpdateGameResponse(builder);
  }

  public static void startUpdateGameResponse(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addStatus(FlatBufferBuilder builder, byte status) { builder.addByte(0, status, 0); }
  public static void addGame(FlatBufferBuilder builder, int gameOffset) { builder.addOffset(1, gameOffset, 0); }
  public static int endUpdateGameResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishUpdateGameResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

